# Generated by Django 5.0.1 on 2024-02-15 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reminder',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
