# Generated by Django 5.0.1 on 2024-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
