# Generated by Django 5.0.1 on 2024-02-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
