# Generated by Django 5.0.1 on 2024-02-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_create_by_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
